### PR TITLE
- Update the timestamp when get a value, Added SetMaxAge(), SetMaxElements()

### PR DESCRIPTION
**Pull request by kibae**

### CODE REVIEW

**Comment by kibae** [comment]
@nkohari 
Most LRU cache implementations have an extended lifetime for get hit of the entry.
If you agree, please merge.

**Comment by kibae** [comment]
@nkohari @karnowski @averyj @micha 
Is there any problems with this patch?

**Comment by karnowski** [comment]
@kibae We'll review it and get back to you!  Thanks for the pull request!

**Comment by karnowski** [comment]
@kibae  Thanks for the PR!  It looks good.  We have no issues with it and would merge it.  However, this is a critical component of our production systems, and we are hesitant to add new features at this time.   Bug fixes are definitely welcome, and if you do fork this project we will be happy to coordinate with bug or security fixes in the future.

**Pull request closed without merging**
